services:
  web-production-server:
    build:
      context: .
      target: web-production-server
    env_file:
      - ./docker.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '80:80'
