services:
  android:
    build:
      context: .
      target: android-release
    env_file:
      - ./docker.env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/src-cordova
      - ./dist:/app/dist
      - ./.gradle:/root/.gradle
